### ISSUE TITLE
Troubles with Posting

### ISSUE THREAD

**Issue by LightSeven** [chrisjaure/JibberBook#1]
when i'm posting on a jibberbook page (for example: http://debusvansinterklaas.nl/gastenboek.php)

i get an error when i post it.. 

now i have changed the value "an error occured" to "the message is post succesfully" but it is strange!
how can i fix it?

**Comment by chrisjaure** [comment]
It seems you did not give write access to the DefinitionCache folder in HTMLPurifier. If you are not able to do this, you should disable HTMLPurifier.
